### ISSUE TITLE
Validate mime type

### ISSUE THREAD

**Issue by NightFox7** [vitiko/IphpFileStoreBundle#20]
How can I validate the mime type of the uploaded file (e.g. check if uploaded file is an image). I tried setting my validation.yml like so:

```
document:
          - NotNull:
          - File:
              maxSize: 4M
              mimeTypes: image/*
              mimeTypesMessage: validation.document.mime  
```

But it doesn't seem to be working.
