### ISSUE TITLE
Field iphp_file don't show completely

### ISSUE THREAD

**Issue by silasrm** [vitiko/IphpFileStoreBundle#40]
Hi,

Congratulation for the bundle, this is great.

I'm using in 4 different entities, but in User entitity, after update to v2.5 or v2.5.1 the file field doesn't appear in form https://cloudup.com/c0COfPVY8yB. In the others, everything is ok https://cloudup.com/cSVF0MSU8sq.

Follow my config: 

```php
//form type
->add(
                'foto',
                'iphp_file',
                array(
                    'label' => 'Foto',
                    'required' => false,
                )
            )
```

```php
// entity 
/**
     * @var array
     *
     * @Assert\File(maxSize="1M", mimeTypes={"image/jpeg", "image/pjpeg", "image/png", "image/x-png"})
     * @FileStore\UploadableField(mapping="foto_usuario")
     * @ORM\Column(name="foto", type="array", nullable=true)
     **/
    protected $foto;
```

```yml
// config
        foto_usuario:
            upload_dir:  %kernel.root_dir%/../web/uploads/usuarios/imagens/
            upload_path: /uploads/usuarios/imagens
            namer:
                property:
                    params: { field : id }
                translit: ~
```

With this same code, but version v0.2.3, all run without problem!

Thank's!
