### ISSUE TITLE
iphp_file not displayed with sonata admin

### ISSUE THREAD

**Issue by Tungenius** [vitiko/IphpFileStoreBundle#46]
Hello,
I have a problem with iphp_file field. I can't display it in Sonata Admin :
```
/**
 * @ORM\Table(name="produit")
 */
class Produit
{
...

    /**
     * @var string
     *
     * @Assert\File( maxSize="20M")
     * @FileStore\UploadableField(mapping="image")
     * @ORM\Column(type="array",nullable = true)
     */
    private $image;
...
}
```

```
iphp_file_store:
    mappings:
       image:
           upload_dir:  %kernel.root_dir%/../web/files
           upload_path: /files
           delete_on_remove:     true
           overwrite_duplicates:  true
           directory_namer:
              property:
                  params: { field : "produitFolder"}
           namer:
               translit: ~
               property:
                   params: { field : id}
```

```
protected function configureFormFields(FormMapper $formMapper)
{
        $formMapper
            ->add('image', 'iphp_file')
}
```

![screenshot-web dev 2016-05-03 13-19-27](https://cloud.githubusercontent.com/assets/3627794/14981746/b927ed98-1131-11e6-96cd-cc5e2e8b22dd.png)
